/*
 * DynNetwork plugin for Cytoscape 3.0 (http://www.cytoscape.org/).
 * Copyright (C) 2012 Sabina Sara Pfister
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

package org.cytoscape.dyn.internal.io.read.xgmml.handler;

import java.util.Stack;

import org.cytoscape.dyn.internal.io.read.xgmml.ParseDynState;
import org.cytoscape.dyn.internal.io.read.xgmml.XGMMLDynParser;
import org.cytoscape.dyn.internal.model.DynNetwork;
import org.cytoscape.dyn.internal.model.DynNetworkFactory;
import org.cytoscape.dyn.internal.view.model.DynNetworkView;
import org.cytoscape.dyn.internal.view.model.DynNetworkViewFactory;
import org.cytoscape.group.CyGroup;
import org.cytoscape.model.CyEdge;
import org.cytoscape.model.CyNode;
import org.xml.sax.Attributes;

/**
 * <code> DynHandlerXGMML </code> implements the interface {@link DynHandler} and
 * handles events generated by the XGMML parser {@link XGMMLDynParser} and generates
 * graph event accordingly.
 * 
 * @author Sabina Sara Pfister
 *
 * @param <T>
 */
public final class DynHandlerXGMML<T> extends AbstractXGMMLSource<T> implements DynHandler 
{
	private final Stack<CyGroup> groupStack;
	private final Stack<OrphanEdge<T>> orphanEdgeList;
	
	private DynNetwork<T> currentNetwork;
	private CyGroup currentGroup;
	private CyNode currentNode;
	private CyEdge currentEdge;
	
	private String directed;
	private String id;
	private String label;
	private String name;
	private String source;
	private String target;
	private String type;
	private String value;
	private String start;
	private String end;
	
	private String h;
	private String w;
	private String x;
	private String y;
	private String fill;
	private String width;
	private String outline;
	
	
	private int ID = 0;
	
	/**
	 * <code> DynHandlerXGMML </code> constructor.
	 * @param networkSink
	 * @param viewSink
	 */
	public DynHandlerXGMML(DynNetworkFactory<T> networkSink, DynNetworkViewFactory<T> viewSink)
	{
		groupStack = new Stack<CyGroup>();
		orphanEdgeList = new Stack<OrphanEdge<T>>();
		this.networkSink = networkSink;
		this.viewSink = viewSink;
	}

	@Override
	public void handleStart(Attributes atts, ParseDynState current)
	{
		switch(current)
		{
		case NONE:
			break;
			
		case GRAPH:
			id = atts.getValue("id");
			label = atts.getValue("label");
			start = atts.getValue("start");
			end = atts.getValue("end");
			directed = atts.getValue("directed");
			label = label==null?"dynamic network ("+(ID++)+")":label;
			id = id==null?label:id;
			directed = directed==null?"1":directed;
			currentNetwork = this.addGraph(id, label, start, end, directed);
			groupStack.push(null);
			break;
			
		case NODE_GRAPH:
			id = atts.getValue("id");
			label = atts.getValue("label");
			start = atts.getValue("start");
			end = atts.getValue("end");
			currentGroup = this.addGroup(currentNetwork, currentNode);
			groupStack.push(currentGroup);
			break;
			
		case NODE:
			id = atts.getValue("id");
			label = atts.getValue("label");
			start = atts.getValue("start");
			end = atts.getValue("end");
			id = id==null?label:id;
			currentNode = this.addNode(currentNetwork, currentGroup, id, label, start, end);
			break;
			
		case EDGE:
			id = atts.getValue("id");
			label = atts.getValue("label");
			source = atts.getValue("source");
			target = atts.getValue("target");
			start = atts.getValue("start");
			end = atts.getValue("end");
			label = label==null?source+"-"+target:label;
			id = id==null?label:id;
			currentEdge = this.addEdge(currentNetwork, id, label, source, target, start, end);
			if (currentEdge==null)
				orphanEdgeList.push(new OrphanEdge<T>(currentNetwork, id, label, source, target, start, end));
			break;
			
		case NET_ATT:
			name = atts.getValue("name");
			value = atts.getValue("value");
			type = atts.getValue("type");
			start = atts.getValue("start");
			end = atts.getValue("end");
			if (currentNetwork!= null && name!=null && value!=null && type!=null)
				this.addGraphAttribute(currentNetwork, name, value, type, start, end);
			break;
			
		case NODE_ATT:
			name = atts.getValue("name");
			value = atts.getValue("value");
			type = atts.getValue("type");
			start = atts.getValue("start");
			end = atts.getValue("end");
			if (currentNode!=null && name!=null && value!=null && type!=null)
				this.addNodeAttribute(currentNetwork, currentNode, name, value, type, start, end);
			break;
			
		case EDGE_ATT:
			name = atts.getValue("name");
			value = atts.getValue("value");
			type = atts.getValue("type");
			start = atts.getValue("start");
			end = atts.getValue("end");
			if (currentEdge!=null && name!=null && value!=null && type!=null)
				this.addEdgeAttribute(currentNetwork, currentEdge, name, value, type, start, end);
			else
				orphanEdgeList.peek().addAttribute(currentNetwork, name, value, type, start, end);
			break;
			
		case NET_GRAPHICS:
			fill = atts.getValue("fill");
			this.addGraphGraphics(currentNetwork, fill);
			break;
			
		case NODE_GRAPHICS:
			type = atts.getValue("type");
			h = atts.getValue("h");
			w = atts.getValue("w");
			x = atts.getValue("x");
			y = atts.getValue("y");
			fill = atts.getValue("fill");
			width = atts.getValue("width");
			outline = atts.getValue("outline");
			if (currentNode!=null)
				this.addNodeGraphics(currentNetwork, currentNode, type, h, w, x, y, fill, width, outline);
			break;
			
		case EDGE_GRAPHICS:
			width = atts.getValue("width");
			fill = atts.getValue("fill");
			if (currentEdge!=null)
				this.addEdgeGraphics(currentNetwork, currentEdge, width, fill);
			else
				orphanEdgeList.peek().addGraphics(currentNetwork, width, fill);
			break;
			
		}
	}

	@Override
	public void handleEnd(Attributes atts, ParseDynState current)
	{
		switch(current)
		{
		case GRAPH:
			while (!orphanEdgeList.isEmpty())
				orphanEdgeList.pop().add(this);
			finalize(currentNetwork);
			break;
			
		case NODE_GRAPH:
			currentNode = groupStack.pop().getGroupNode();
            currentGroup = groupStack.peek();
			break;
		}
	}

	@Override
	protected CyEdge addEdge(DynNetwork<T> currentNetwork, String id, String label,
			String source, String target, String start, String end)
	{
		return networkSink.addedEdge(currentNetwork, id, label, source, target, start, end);
	}

	@Override
	protected void addEdgeAttribute(DynNetwork<T> network, CyEdge currentEdge,
			String name, String value, String Type, String start, String end)
	{
		networkSink.addedEdgeAttribute(network, currentEdge, name, value, Type, start, end);
	}
	
	@Override
	protected void addEdgeGraphics(DynNetwork<T> network, CyEdge currentEdge, 
			String width, String fill)
	{
		viewSink.addedEdgeGraphics(network, currentEdge, width, fill);
	}
	
	@Override
	protected DynNetworkView<T> createView(DynNetwork<T> dynNetwork)
	{
		// Do nothing.
		return null;
	}
	
}
