package org.cytoscape.dyn.internal.read.xgmml.handler;

import org.cytoscape.dyn.internal.read.xgmml.ParseDynState;
import org.xml.sax.Attributes;

/**
 * <code> DynHandler </code> is the interface for handling events generated by
 * a parser.
 * 
 * @author sabina
 *
 */
public interface DynHandler
{	
	/**
	 * Handle start event.
	 * @param atts
	 * @param current
	 */
	public void handleStart(Attributes atts, ParseDynState current);
	
	/**
	 * Handle end event.
	 * @param atts
	 * @param current
	 */
	public void handleEnd(Attributes atts, ParseDynState current);
}
